apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-app-db-statefulset
spec:
  selector:
    matchLabels:
      app: billing-app-db-statefulset
  serviceName: billing-app-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: billing-app-db-statefulset
    spec:
      containers:
      - name: billing-database-container
        image: jesuskris/billing-database:1.0.1
        readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
            initialDelaySeconds: 10
            periodSeconds: 5
        resources:
        volumeMounts:
        - name: billing-database-volume
          mountPath: /var/lib/postgresql/data
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgresql-secrets
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secrets
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: postgresql-secrets
                key: BILLING_POSTGRES_DATABASE
  volumeClaimTemplates:
  - metadata:
      name: billing-database-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
