apiVersion: v1
kind: Service
metadata:
  name: inventory-app-db-service
spec:
  type: ClusterIP
  selector:
    app: inventory-app-db-statefulset
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None