apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: api-gateway-deployment
  ports:
    - protocol: TCP
      port: 1024
      targetPort: 1024