apiVersion: v1
kind: Service
metadata:
  name: billing-app-service
spec:
  type: ClusterIP
  selector:
    app: billing-app-statefulset
  ports:
    - protocol: TCP
      port: 1024
      targetPort: 1024
  clusterIP: None