apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
data:
  RABBITMQ_PORT: NTY3Mg== #5672
  RABBITMQ_QUEUE: YmlsbGluZ19xdWV1ZQ== #billing_queue
  RABBITMQ_USER: ZGV2X3VzZXI= #dev_user
  RABBITMQ_PASSWORD: ZGV2X3Bhc3M= #dev_pass
  RABBITMQ_IP: "cmFiYml0bXEtc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs" #rabbitmq-service.default.svc.cluster.local
